module.exports = [

{name: 'Checkin & Coffee',
 day: 1,
 from: '08:00',
 to: '09:30',
 track: -1,
},
{name: 'Welcome speech',
 day: 1,
 track: -1,
 from: '09:30',
 to: '09:45'
},

{name: "CSS3: the web's Swiss Army Knife updated and improved", 
 day: 1,
 from: '09:45', 
 to: '10:45',
 speaker: 'Stephanie Sullivan',
}, 
{name: 'HTML5 APIs: Where no man has gone before',
 day: 1,
 from: '10:45',
 to: '11:45',
 speaker: 'Robert Nymann'
},
{name: 'Coffee Break',
 track: -1,
 day: 1,
 from: '11:45',
 to: '12:15'
},
{name: 'Datos Abiertos en Chile',
 day: 1,
 track: 1,
 from: '12:15',
 to: '12:45',
 speaker: 'Andres Bustamante'
},
{name: 'Ciudadano Inteligente',
 day: 1,
 track: 1,
 from: '12:55',
 to: '13:25',
 speaker: 'Pedro Daire'
},
{name: 'Lunch',
 day: 1,
 track: -1,
 from: '13:25',
 to: '15:00'
},
{name: 'Modelo de Madurez para OpenData',
 day: 1,
 track: 1,
 from: '15:00',
 to: '15:30',
 speaker: 'Luis Meijueiro'
},
{name: 'La Web Ha Muerto. El Futuro: Web APIs',
 day: 1,
 track: 1,
 from: '15:40',
 to: '16:10',
 speaker: 'Ernesto Tagwerker'
},
{name: 'Lessons Learned from the Development of a Web Conferencing System',
 day: 1,
 track: 1,
 from: '16:20',
 to: '16:50',
 speaker: 'Markos Calder&oacute;n'
},
{name: 'Coffee Break',
 day: 1,
 track: -1,
 from: '16:50',
 to: '17:15'
},
{name: "Fake it 'til you make it: creating mobile apps that feel like native apps",
 day: 1,
 from: '17:15',
 to: '18:15',
 speaker: 'Jonathan Snook'
},
{name: 'Lightning Talks',
 day: 1,
 from: '18:15',
 to: '19:30',
},
{name: 'Github Drink-up ( Cervezas y Networking )',
 day: 1,
 from: '19:30',
 to: '22:00',
 track: -1
},


/* Track 2 */
{name: "jQuery('#knowledge') .appendTo('#you')",
 day: 1,
 track: 2,
 from: '12:15',
 to: '13:25',
 speaker: 'Mike Hostetler'
},
{name: 'Building Languages for the JVM',
 day: 1,
 track: 2,
 from: '15:00',
 to: '16:10',
 speaker: 'Charles Nutter',
},
{name: 'Developing Findability Standards',
 day: 1,
 track: 2,
 from: '16:20',
 to: '16:50',
 speaker: 'Ravi Mynampaty'
},

/* Track 3 */
{name: 'Start Using HTML5 Today with Polyfills and Shims',
 day: 1,
 track: 3,
 from: '12:15',
 to: '13:25',
 speaker: 'Ray Bango'
},
{name: 'ChileAyuda: Un terremoto, 300 voluntarios y 6 días para construir un portl',
 day: 1,
 track: 3,
 from: '15:00',
 to: '15:30',
 speaker: 'Pedro Fuentes'
},
{name: 'Que mantener, arreglar e intentar en la industria chilena de software',
 day: 1,
 track: 3,
 from: '15:40',
 to: '16:10',
 speaker: 'Agust%iacute;n Villena',
},
{name: 'C&oacute;mo construimos e hicimos crecer una empresa de consultor&iacute;a Rails',
 day: 1,
 track: 3,
 from: '16:20',
 to: '16:50',
 speaker: 'Stephen Andreson'
},


/* 5 Nov */
{name: 'Checkin & Coffee',
 day: 2,
 track: -1,
 from: '08:00',
 to: '09:00'
},
{name: 'Developing HTML5 For a Cross Browser World',
 day: 2,
 from: '09:00',
 to: '10:00',
 speaker: 'Paul Irish'
},
{name: 'Relational vs !Relational',
 day: 2,
 from: '10:00',
 to: '11:00',
 speaker: 'Mark Ramm',
},
{name: 'Coffe Break',
 day: 2,
 track: -1,
 from: '11:00',
 to: '11:30'
},
{name: 'Using jQuery Mobile',
 day: 2,
 from: '11:30',
 to: '12:40',
 speaker: 'Mike Hostetler',
 track: 1,
},
{name: 'Monkey, HTTP server everywhere.',
 day: 2,
 from: '12:50',
 to: '13:20',
 speaker: 'Eduardo Silva',
 track: 1,
},
{name: 'Lunch',
 day: 2,
 track: -1,
 from: '13:20',
 to: '15:00',
},
{name: 'Web Scraping for Development of Mobile and Web interfaces',
 day: 2,
 from: '15:00',
 to: '15:30',
 speaker: 'Alvaro Aguirre',
 track: 1,
},
{name: 'Movistar Innova y plataforma Bluevia',
 day: 2,
 from: '15:00',
 to: '15:30',
 track: 1,
},
{name: 'Desarrollo móvil multiplataforma: ¿Por dónde empez',
 day: 2,
 from: '16:30',
 to: '16:50',
 track: 1,
 speaker: 'Abraham Barrera'
},
{name: 'Coffe Break',
 day: 2,
 track: -1,
 from: '16:50',
 to: '17:15',
},
{name: 'Move it! CSS3 Transitions and Animations',
 day: 2,
 from: '17:15',
 to: '18:15',
 speaker: 'Greg Rewis',
},
{name: 'Optimizing for Happiness',
 day: 2,
 from: '18:15',
 to: '19:15',
 speaker: 'Tom Preston-Werner',
},
{name: 'Checkout',
 day: 2,
 track: -1,
 from: '19:15',
 to: '19:30'
},

/* track 2 */
{name: 'PostgreSQL with all good features of NoSQL',
 day: 2,
 track: 2,
 from: '11:30',
 to: '12:00',
 speaker: 'Hannu Krosing'
},
{name: 'A Tale of Three Trees',
 day: 2,
 track: 2,
 from: '12:10',
 to: '12:40',
 speaker: 'Scott Chacon',
},
{name: 'Post mortem: 24h, 72 DDoS',
 day: 2,
 track: 2,
 from: '12:50',
 to: '13:20',
 speaker: 'Tomas Pollak / Carlos Yaconi',
},
{name: 'Performance analysis of Rails 3 applications',
 day: 2,
 track: 2,
 from: '15:00',
 to: '15:30',
 speaker: 'Gonçalo Silva',
},
{name: 'JRuby: Ruby en un mundo enterprise',
 day: 2,
 track: 2,
 from: '15:40',
 to: '16:10',
 speaker: 'Jano Gonzalez',
},
{name: 'Shaven - Templating without mustaches',
 day: 2,
 track: 2,
 from: '16:20',
 to: '16:50',
 speaker: 'Chris Kowalik'
},





/* track 3*/
{name: 'Administración ágil de sistemas en el entorno de una Startup',
 day: 2,
 track: 3,
 from: '11:30',
 to: '12:00',
 speaker: 'Fernando Blat',
},
{name: 'To Test ot Not To Test',
 day: 2,
 track: 3,
 from: '12:10',
 to: '13:20',
 speaker: 'Obie Fernandez',
},
{name: 'Programación paralela en plataforma Java es fácil con Groovy y Grai',
 day: 2,
 track: 3,
 from: '15:00',
 to: '15:30',
 speaker: 'Daniel Arsenovski',
},
{name: 'Conquering the Server Side with Node.JS',
 day: 2,
 track: 3,
 from: '16:20',
 to: '16:50',
 speaker: 'Cardy Patiño',
}

]
